### ISSUE TITLE
About compute_openauc(x1, x2, pred, labels) 

### ISSUE THREAD

**Issue by Fulin-Gao** [wang22ti/OpenAUC#2]
Is the parameter introduction in ‘’compute_openauc(x1, x2, pred, labels)‘’ correct? We found that even if all samples were classified into known classes, the output of openauc was still very high.

**Comment by wang22ti** [comment]
OpenAUC only focuses on the ranking of open-set scores, whereby a higher x1/x2 value indicates a higher probability of the sample being an open-set sample. It is recommended to check whether the input score is increasing w.r.t. the probability of the sample being an open-set sample.

**Comment by wang22ti** [comment]
Here is an example: 

x1 = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
x2 = np.array([0, 0, 0, 0.9, 1.0])
pred = np.array([0, 1, 2, 3, 0])
labels = np.array([0, 1, 2, 3, 4])

The output is 0.32, which is consistent with the formulation described in our paper.

**Comment by Fulin-Gao** [comment]
Thank you very much for your kind reply, but I am still a bit confused. May I provide an example, could you please provide x1, x2, pred, labels？
known classes: 0, 1; unknown classes: 2; 

| Sample No. | True labels | Predict labels | Predict score on classes 0, 1, 2
|--------|--------|--------|--------|
|  1            | 0                  | 0                       | [0.9, 0.1, 0.0]
| 2           | 0                  | 0                       | [0.8, 0.1, 0.1]
| 3           | 1                   | 1                       | [0.1, 0.9, 0.0]
| 4           | 1                   | 1                       | [0.1, 0.8, 0.1]
| 5           | 2                  | 0                       | [0.9, 0.0, 0.1]
| 6           | 2                  | 0                       | [0.8, 0.1, 0.1]
| 7           | 2                  | 1                       | [0.0, 0.9, 0.1]
| 8           | 2                  | 1                       | [0.1, 0.8, 0.1]


Thank you!

**Comment by Fulin-Gao** [comment]
We urgently need your help and hope that you can reply when you see it. Thank you.

**Comment by wang22ti** [comment]
The example is indeed a little confusing since it puts the scores of known classes and the unknown class together. In other words, the final prediction is calculated by argmax [s_1, s_2, s_3]. However, since no open-set sample is available during the training phase, such a decision-making process might be unreasonable.

In fact, for open-set learning, we generally assume that the final prediction is made by a meta-classifier. To be specific, in the first stage, a rejector, which only takes the open-set score as the input, decides which samples are unknown. In the second stage, a classifier will decide which class the close-set samples belong to. For example, let x1 be a close-set sample, and s(x1) = (0.5, 0.1, 0.4). According to your idea, since 0.5>0.4, its predict label is 0. However, in the first stage, we only check whether 0.4 is greater than a pre-defined threshold t. If 0.4 > t, the predict label is 2. If 0.4 < t, the predict label is 0.

OK, keep this in mind, and let's check your example:
x1 = np.array([0.0, 0.1, 0.0, 0.1]) # open set score for each known class sample (Sample No.1,2,3,4)
x2 = np.array([0.1, 0.1, 0.1, 0.1]) # open set score for each unknown class sample (Sample No.5,6,7,8)
pred = np.array([0, 0, 1, 1]) # predicted class for each known class sample (Sample No.1,2,3,4)
labels = np.array([0, 0, 1, 1]) # correct class for each known class sample (Sample No.1,2,3,4)

In fact, this example is not good since the open-set scores have too many ties. That is, we only have two values, 0.0 and 0.1 for open set score. It is recommended to assign more values. 

Hope this comment can address your issue : )
If you are still confused, please refer to the preliminary part of our paper, where the decision-making process has collaborated.

**Comment by Fulin-Gao** [comment]
Thank you very much for your patient reply!

We evaluated the probability of samples belonging to unknown classes through a method, and in this method, we can continuously adjust the proportion of unknown probabilities through a parameter. In this case, we want to use your metric (OpenAUC) to determine the best value for the parameter.

However, we find that when we adjust the parameter so that all unknown probabilities are 0 (that is, all open set samples are grouped into known classes), OpenAUC=0.8. And in the process of increasing the proportion of unknown probability, OpenAUC continues to decline, rather than the expected first rise and then decline. This leaves us at a loss. 

Using the x1, x2, pred, labels you gave above, we get OpenAUC=0.75. Obviously, 0.75 is also a bit large; after all, this bad example also puts all open set samples into known classes.

**Comment by wang22ti** [comment]
ummmm, please review the decision-making process, OpenAUC=0.75 is not a large value:
x1 = np.array([0.0, 0.1, 0.0, 0.1]) # open set score for each known class sample (Sample No.1,2,3,4)
x2 = np.array([0.1, 0.1, 0.1, 0.1]) # open set score for each unknown class sample (Sample No.5,6,7,8)
OpenAUC = (8 + 8 * 0.5) / (4 * 4), 
where "8" comes form the fact that all the unknown class samples are ranked higher than samples with No.1,3, and (8 * 0.5) comes from the ties (i.e.,  samples with No.2,4 have the same open-set score as the unknown samples).

you say "after all, this bad example also puts all open set samples into known classes." This exactly is why you are confused. To be specific, you still make predictions by argmax [s_1, s_2, s_3]. However, as described before, you should first check whether the open set score is higher than a threshold. In this "bad" example, if we choose "t = 0.05", all the open-set samples and 2 close-set samples will be correctly classified. Of course, if you choose "t = 0.2", all the open-set samples will be classified into known classes. However, this bad prediction only holds under the given threshold. As we described in our paper, OpenAUC aggregates the performance under all possible thresholds.

Please remember that do not make predictions by argmax. It will be helpful to rethink the decision-making process.

**Comment by wang22ti** [comment]
When calculating OpenAUC, please do not pre-assume that some open-set samples have been misclassified since OpenAUC aims to aggregate the performance under different thresholds. In fact, being insensitive to the threshold selection is exactly our motivation

To check the OpenAUC value, you should check the ratio of correct ranking pairs between the open-set samples and close-set samples, as the operation in the last comment.

**Comment by Fulin-Gao** [comment]
You're right. Thank you very much for your guidance. Now I understand and recognize your work!

We wanted to directly measure OSR performance without thresholds, so it seemed that I needed to look for other metrics that were more appropriate.

Thanks again! 🙏
